# Generated by Django 6.0.4 on 2026-05-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
