# Generated by Django 6.0.4 on 2026-05-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0002_remove_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Total_cost',
            new_name='total_cost',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
