# Generated by Django 6.0.4 on 2026-05-13 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0003_rename_total_cost_stock_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nyondoapp.product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
