# Generated by Django 6.0.4 on 2026-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0004_supplier_product_alter_supplier_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
