# Generated by Django 6.0.4 on 2026-05-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0006_supplier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
