# Generated by Django 6.0.4 on 2026-05-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0007_sale_transport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nyondoapp.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20),
            preserve_default=False,
        ),
    ]
