# Generated by Django 6.0.4 on 2026-05-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0008_rename_amount_sale_total_amount_remove_sale_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total_amount',
            new_name='sub_total',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
        migrations.AddField(
            model_name='sale',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
