# Generated by Django 6.0.4 on 2026-05-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0009_rename_total_amount_sale_sub_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
