# Generated by Django 6.0.4 on 2026-05-20 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_supplierpayment'),
        ('nyondoapp', '0010_payment_amount_paid_alter_payment_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.supplier'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
