# Generated by Django 6.0.4 on 2026-05-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0011_alter_stock_supplier_delete_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepositScheme',
        ),
    ]
