# Generated by Django 6.0.4 on 2026-05-29 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0013_alter_employee_gender_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='nyondoapp.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='nyondoapp.sale'),
        ),
    ]
