# Generated by Django 6.0.4 on 2026-06-02 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0002_sync_database_schema'),
        ('nyondoapp', '0014_sale_payment_alter_payment_order_id'),
    ]

    operations = [
    ]
