# Generated by Django 6.0.3 on 2026-06-02 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0016_fix_missing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_reference', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('utilities', 'Utilities (Water, Electricity)'), ('rent', 'Rent/Premises'), ('transport', 'Transport & Fuel'), ('salary', 'Staff Salary'), ('supplies', 'Office Supplies'), ('maintenance', 'Maintenance & Repairs'), ('advertising', 'Advertising & Marketing'), ('insurance', 'Insurance'), ('professional', 'Professional Services'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('card', 'Bank Card'), ('bank_transfer', 'Bank Transfer')], max_length=30)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
