services:
  - type: web
    name: nyondo-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn nyondohardware.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: nyondo-app.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://nyondo-app.onrender.com

databases:
  - name: nyondo-db
    databaseName: nyondo
    user: nyondo