# Generated by Django 6.0.4 on 2026-05-20 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_supplierpayment'),
        ('nyondoapp', '0011_alter_stock_supplier_delete_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nyondoapp.product'),
        ),
    ]
