# Generated by Django 6.0.4 on 2026-05-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_supplier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
