# Generated by Django 6.0.4 on 2026-05-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_depositscheme_depositpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositscheme',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
