# Generated by Django 6.0.4 on 2026-05-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_depositpayment_receipt_number_depositwithdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='product',
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='depositscheme',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed'), ('Withdrawn', 'Withdrawn'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
